version: '3.8'

services:
  appgate-social-media-analyzer:
    container_name: appgate-social-media-analyzer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Bogota
