version: '3.8'

services:
  appgate-challenge:
    container_name: appgate-social-media-analyzer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Bogota
      - LOGBACK_CONF=/home/app/logback-spring.xml
