version: '3.8'

services:
  appgate-challenge:
    container_name: appgate-challenge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Bogota
      - LOGBACK_CONF=/home/app/logback-spring.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
